environments:
  default:
    env_vars:
      DROOLS_BUILD_MVN_OPTS: -Dfull
  native:
    env_vars:
      NATIVE: true
      BUILD_MVN_OPTS_CURRENT: -Dnative -Dquarkus.native.container-build=true
      DROOLS_BUILD_MVN_OPTS: -Dfull
      ADDITIONAL_TIMEOUT: 720
    ids:
    - native
  quarkus-main:
    enabled: false
    env_vars:
      QUARKUS_BRANCH: main
      DROOLS_BUILD_MVN_OPTS: -Dfull
    ids:
    - quarkus
  quarkus-3:
    pull_request_default_check: false
    env_vars:
      BUILD_MAVEN_TOOL: maven_3.9.1
      BUILD_JDK_TOOL: jdk_17_latest
      BUILD_MVN_OPTS: -Denforcer.skip
      # DROOLS_BUILD_MVN_OPTS: -Dfull #  "No enabled as it does not compile in quarkus-3
      # BUILD_MVN_OPTS_QUARKUS_UPDATE: -Dfull
    ids:
    - quarkus
    - quarkus3
  quarkus-branch:
    env_vars:
      QUARKUS_BRANCH: '2.16'
      DROOLS_BUILD_MVN_OPTS: -Dfull
    ids:
    - quarkus
  sonarcloud:
    auto_generation: false
    env_vars:
      ENABLE_SONARCLOUD: true
      DROOLS_BUILD_MVN_OPTS: -Dfull
    ids:
    - sonarcloud
    - coverage
disable:
  triggers: false
repositories:
- name: drools
- name: drools-website
- name: kie-benchmarks
# - name: kie-jpmml-integration ## TODO to check if enabled
git:
  author:
    name: kiegroup
    credentials_id: kie-ci4
    token_credentials_id: kie-ci4-token
  fork_author:
    name: kie-ci
    credentials_id: kie-ci
  quarkus:
    author:
      name: quarkusio
      credentials_id: kie-ci
    branch: main
  jenkins_config_path: .ci/jenkins
buildchain_config:
  git:
    repository: drools
    file_path: .ci/buildchain-config.yaml
maven:
  settings_file_id: kie-release-settings
  nexus:
    release_url: https://repository.jboss.org/nexus
    release_repository: jboss-releases-repository
    staging_profile_url: https://repository.jboss.org/nexus/content/groups/kogito-public/
    staging_profile_id: 1976dd1c18392a
    build_promotion_profile_id: ea49ccd6f174
  artifacts_repository: ''
  artifacts_upload_repository:
    url: https://repository.jboss.org/nexus/content/repositories/snapshots/
    creds_id: kogito-snapshots-upload
  pr_checks:
    repository:
      url: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/repositories/kogito-runtimes-pr-full-testing/
      creds_id: unpacks-zip-on-qa-nexus
cloud:
  image:
    registry_credentials_nightly: nightly_kogito
    registry_credentials_release: release_kogito
    registry: quay.io
    namespace: kiegroup
    latest_git_branch: main
jenkins:
  email_creds_id: KOGITO_CI_EMAIL_TO
  default_tools:
    jdk: jdk_11_latest
    maven: maven_3.8.6
    sonar_jdk: jdk_17_latest
