ecosystem:
  main_project: drools
  projects:
  - name: drools
    regexs:
    - drools.*
  - name: kie-jpmml-integration
    ignore_productization: true
    regexs:
    - kie-jpmml-integration.*
git:
  branches:
  - name: 9.x
    main_branch: true
    seed:
      branch: main
      config_file:
        git:
          branch: 9.x-dsl-config
  - name: 9.44.x
    seed:
      branch: seed-drools-9.44.x
      config_file:
        git:
          branch: drools-9.44.x
seed:
  config_file:
    git:
      repository: drools
      author:
        name: kiegroup
        credentials_id: kie-ci4
      branch: 9.x-dsl-config
    path: .ci/jenkins/config/branch.yaml
  jenkinsfile: dsl/seed/jenkinsfiles/Jenkinsfile.seed.branch
jenkins:
  email_creds_id: KOGITO_CI_EMAIL_TO
