ecosystem:
  main_project: drools
  projects:
  - name: drools
    regexs:
    - drools.*
  - name: kie-jpmml-integration
    regexs:
    - kie-jpmml-integration.*
  - name: kie-benchmarks
    ignore_release: true
    regexs:
    - kie-benchmarks.*
git:
  branches:
  - name: apache_migration
    main_branch: true
seed:
  config_file:
    git:
      repository: drools
      author:
        name: kiegroup
        credentials_id: kie-ci4
      branch: apache_migration
    path: .ci/jenkins/config/branch.yaml
  jenkinsfile: dsl/seed/jenkinsfiles/Jenkinsfile.seed.branch
jenkins:
  email_creds_id: KOGITO_CI_NOTIFICATION_EMAILS
